#include "essential_head.hh"

#include "net/tcpsvr.hh"
#include "net/echosvr.hh"
#include "actor/mgr.hh"
#include "actor/task.hh"

#include <cstring>
#include <iostream>
#include <signal.h>

#include "proto/test.pb.h"

last::net::echosvr* echosvr;

void shut_down(int sig) {
    print("[signal] : recv sig: %d", sig);
    // 调用echosvr::shut_down()函数停止服务
    echosvr->shut_down();
    delete echosvr;
    print("has shut down");
    ::exit(0);
}

int main(int argc, char** argv) {
    last::log::logger::get_inst()->init();

    print("gcc version:", __GNUC__);
    print("current cpp version:", __cplusplus);
    print("main thread id is:", ::syscall(SYS_gettid));

    ::signal(SIGTERM, shut_down);
    ::signal(SIGINT, shut_down);

    last::actor::mgr mgr;
    mgr.create<last::actor::actor>();
    mgr.create<last::actor::actor>();
    mgr.create<last::actor::actor>();

    ::sleep(1);
    for(uint16_t i = 0; i < 40; ++i) {
        auto task = std::make_unique<last::actor::task>();
        task->id = 1000 + i;
        mgr.send(last::actor::def::actor, std::move(task));
    }

    // echosvr = new last::net::echosvr("0.0.0.0", 8765, 4, 2);
    // echosvr->start();

    ::sleep(20);
    return 0;
}

/*
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;,,,''..',;;,,;;;;;;:::::::;;;,,,,,,;;:::::::::::::::::::::::::::::::::;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::::::::::::::::::::::::;;;,'...........     ..............',:::;;;;,.......',;::::::::::::::::::;;,'...............'',;;,,,,;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::::::::::::::::;,'........     ..',:ldxxolclo:.. ...,;:coxOKNWWNWWWNKkl:;'.. ...'',;:::::::;,'...........',,;;:clodxxO0Odooool:,,,;,'.,;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::;;,,'..........''...',;ldk0XNWWWWWWNKxlldk0KXNWWMMWWWXOkOKNN0xc;;:cc;....  ..',;,.......',;;:looxKXKXXWWMMMMMMMMMMMMMMWNXXXKOdolc,''..'',;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::,....   ..';:colcc;.,codkXNWWWWNXWWMMWNWWWMMMMNXWMWWNWWX00XWWWWWXkoccool:,,..   .. ..',,;okxxdlccdXMMMMMWKOOKNWWNWMMMMMMMMMMMMMMMMWX0Okdoc;....',;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::;..     ..,:ccldxl:'.'okO0NWWWWW0xKWWMWWWWMWWWXxd0WMWWMMMWWWWMMMMMMMMMMMMMN0xc'.   .',,..:kK0Od:cd0WMMNKkl:'.;oxdc;;lkKWMMMMMMMMMMMMMMMMMMMMNKo.   ..,:::::::::::::::::::;;,'''',,,,;;;;;;;,,,,''''',,;;::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::::,.      .';:::lxdlc,..ckkOKNWWWWXx0WWWMWMWNKxx00kKWWWMMMMMMWWWMMMMMMMMMMMMMMMWXl. ..,'..'oXMWKo:xNMWKxoc,''...';:ccllccodxddk00XNWMMMMMMMMWNXXXKx;.   ..,;:::::::::::;,',;:llodkO00KKXXXXXXXKK0OOkxdlc::;,''',,;:::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::,.      .,:;;:cxxlc:. .ckkO0XNWNW0ONXKWWMNOl:ckXWMMWMMWMWMMWWWWMMMMMMMMMMMMMMMM0, ......cKWWNKol0K00d;:k0xdxxxOKNWWMMMMMWWNKkdddxkOOXWMMMWXOkkkkkkxl,..   .',:::::,'';clxOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOxolc;,''',;:::::::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::;.        ';'';lOxlc;. .;xkO0K00OKKXWkldkOdcccdXWMMMMMMMWNK0O0XWMMMMMMWNNNWWWWWWo. .....;KMNk:.'lxc;,.'codod0NN0xdddooodkKKKNMMMMMMMNNWMWNKOdc;;;;:clc,.     ..,,,;cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdl:,''',;::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::'.  ..    .'..,codoc'...'lk0KKOxx0KXXl'..,lxdckWMWWWWN0ko;'...,cd0NWNXK000XXXXXXo. ... .lNWk'...;ol:,...,cl:;;'..       ...'cdxxxxkOKWMMWX0OOxl:,...,;;,'..   .'lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc;''';;::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::;.       .......:c:,.... .;xOKKOxxOk00,...lK0clXMWNK000OOOOkdc,....,:::cldOKKKKKKd. ... .oXKl.. .cxxc'';:cloollccc:::;'......'codkkOO0X0KWNK0OOkxdl:,',;;,'. .;dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0o:,'',;:::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::;.       ...   .'c;.....  'loxXKkdkxkO,..cXWk:xNNKkOKNWWNXXNWWKOxolccc:;,;lxO0000o. .. ..cKkc'. 'x0Odx0NXXNMMMMWNNXKKKOxdoooc;:okXNMMMWXXWMWNX0kxxddddol;...cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNWWN0ko:'.',:::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::'.              .,c,..... .;olcoxxxKNNd';OWW0kXWWWWMWWWWKOkocllloxkOO00OOkxxxxk0x,.. ... .xKKOdd0WMWWMMMMMMMMMMMMMMMMMWWX0000o;,,;:ldxk0NWMMMMWXKOkkkxd:'.cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdoddONNKK0kl;'.';::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::.              ..:ol'.......;o:.:O0XWWNKXWWWWWWWWMMMMWWWWWWXd;..',,,,lO00000Okdc'...,.....xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNXOxddooooooooxOXWMWNNXOl',oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkolc;:o0NNKOko:..',;:::::::::::::::::::::'      
'::::::::::::::::::::::::::::,.         ....':oxxl;,'',;,:xOxkXWWMWWWWWWWWWWWMMMMMMMWWMMMMN00KKkc..:ooooodx:..':lo:'cxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKXKx:',:oONWKc'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKoloc''cdkOOOxl;...,;:::::::::::::::::::'      
'::::::::::::::::::::::::::::;..      ..',,;:coxdolcllldkXWWWWMWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMNOoc:,.......cdxdk0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkoool:;,''co,'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0lcodc,'..;lodoc;...,::::::::::::::::::'      
':::::::::::::::::::::::::::::'.    ..,,,;:lodkkkkxxdkKNWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMWX0kxxd:. .;dO00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc'';:ll:.'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,;loc;,....',,;,'..';::::::::::::::::'      
':::::::::::::::::::::::::::;..   ..,;,,:lodxO0KKKKKKNWMMWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMWk;.,:;.'o0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'..',.,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMO:,';:;,,'......'......';::::::::::::::'      
'::::::::::::::::::::::::::;.    .';,',:odxk0XNNWWWWMMMMMMWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMXd'. .:ONWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0k:....xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMWWMMWNWMM0:;;,;:;''.....':c,......,:::::::::::::'      
':::::::::::::::::::::::::;..   .';,'';odxOKNWWWWWMMMMMMMMMWWWWWWWWWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWXd'.:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc',...cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMWNNXNWWNWMWXOdl:,,::,''.....';:;'.   ..,;::::::::::'      
':::::::::::::::::::::::::'.    .',''':oxOKNWWWWMMMMMMMMMMMMMMMMMMWMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWKl.:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,....kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKXNWWWWWKkdoc:cccc;,'.........','....  .';::::::::'      
'::::::::::::::::::::::;'..    ..''',,cdOXWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKx,:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,..cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKXWWNNWNOxo;'.'cooc;,.................   .;:::::::'      
':::::::::::::::::::::,.       ..',;:clxKWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKk;,kNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo''OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWXXXWNXXXKOkd:'..'lxocc;'...,'...........  .':::::::'      
':::::::::::::::::::;'.       ..',;:cod0NWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0c'lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xl'lXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMWXKXK00Okkkkxl;'.'lxolc;..':c:'..........  ..;:::::'      
'::::::::::::::::::;.         ..'',codxXMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKd':kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMWOdd;,kNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWXKXWNWWMMMMMMMMMWWWWWNNWWWNKK0OxxxkOOkxddl;.'cdolc;,:oxxdl,.........  .':::::'      
'::::::::::::::::::.... ...   ..'',cddxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0Ok:'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMNOolc':0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKXXKO0NWWMMMMMMMWWWX0XXXNX0O0KKOOkxxkO00Oxolddc'.;lc:cldxkOOOkl'........  .:::::'      
'::::::::::::::::;...;' ...   .'',;codxKWWWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOdc.;xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMWWNXXXXkc;:'.oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKXKNWWWWWMMMMMMWWW0kkxkXKkxdxdxOOkkO00KKKkxOxccodo:..;cldkO0KKKKK0l:l:;:,.  .;::::'      
'::::::::::;,''... .,:'...    ..',:clox0NNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOkdc'.:kXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXNNOkKNNNWWWKkkKNKo:,'.'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0O0XNWWMMMMWNX0xolldOKKKNMNOdddoxxxkkOO0Oxdodkxo:;cdkd:,:x0KXK0xdxxxl;llcc,.  .;::::'      
':::::::::;.     ..,::'.,.    ..';:::ok0XKNWWWWWWNXXWMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMWXK0Odc'..lk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXXKkoddddk0kod00dc;...,OWWWWWMMMMMMMMMMMMMMMMMMMMWNXXKKKKXX0kxdoll:;'.......;okXWMMN0xdkxxkOkkxolooolloc:lxKWNKxldxdl:;;;:c:'.'';'.  .;::::'      
'::::::::;.  ...,;::;'','.    .',;::ckNWNNNNWWNX0xookXWWNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMWNK0xc...ckkO0XWMMMMWNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN00WNOdxxolddclxdl;'...:KWNNNNWWMMWWWWMMMMWNNXXXXNWX00KX0xl;'..        ..''.....'cxXWWX0Okkxdddxdoooool;cxXxlKMNOdlllc::;,'''..  ..   .,::::'      
':::::::;.  ..':::;'.....   ..';:cld0NWMMMMMMW0doolok0XNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0d;...,xXNXXNWMMMMWXOO0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMWXKOdooooolc;,'..cKWWWNXXXXNXK0XNWMMWN0xolc::okxoc,...        ..:xOKXK0kdlc:,,:loOXOxxdoooddool:coccokk;;kNNKkdoooollc;.....     .'::::'      
'::::::;.. ...';:;.....    .';cdkkOXWMMMMMMMMMN0xxKNWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWX0x:..,lOK0O0NMMMMMMMNklOWMMMMMMMMMMMMMMMMMWWNNWWWWWMMMMMMMMMMMMMMMMNOooool:,'.':dOKXWMWNKkddxxO0kkKNWNk:,'......             ..':xKWMMMWWNXK0Oxl,'dK0koooocccc;,:ccc;;dk:':dO000OOkOOOo,...       .;:::'      
'::::,..  ....',....'..  ..,cxKWMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0OKX0kxc. ..;c:;,';ldxKWMWXo,l0XNMMMNkdolclxxdlc:;'';;;:cloooolokXMMMMMMMMNOoll:'.. .,'..,:lloc,'',:cllxKNWWKo,....  ....    ...........,lxO0KXNNNNX0kd;,oOxodolc:::;:c::::,;dOxc'.';lxOKXKK0x;.        .':::'      
':::'.   ... ... ....   ..cOXWMMMMMMMMMMMMMMMNXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMWWWKkxxkkkkkc... ....      .lxko:;::;;llc,.             . ..,,'.....'';dKWMMMMWN0oc:'..                ..'oKNWMWWWN0c..   ...    ....';coddooc;,,;:loooolc::;'',:locccccllloddl;,'':dko:'....,cdk0Kk;.        ':::'      
'::;.          .....   .';oO0kddodKWMMMWWWWWNX0xdxONMMMMMMKdxkxk00KXWMMMMMMMWWWWN0kxxxxxko'.......',,......',:dxl'.               .:lloxOOxollllodxoolldx0WWNOl:;''.                  .dNMMMMMMMXl'.. ..          ...,;:cllc:;....'',;,'.''...;:;;:;;;;okOOd;;:;'.',;;;,'..  ..,:c'        ':::'      
':::;.   ... .....     .'.........;xKK0OxdxKKdc:,',oKOxxxo,....';:cok0KXNWMMMWWWWWKOOkddxoc;,....;:;,'......'xWWXx:.    .......   .,::ccoOXXXKXXNNNX0xl'.'o00d;::;,....     .'',,'..   ;KMMMMMWKo,'......      .     .,;'................'''';ldolc:;;cdkO0xlcldo:'.....'',..    ... .     ':::'      
'::::.   ..  ...       .'.  .... ...,;,''',cdl'... ....    ....   ..',:lld0WWWWWWWNKOkxxxdoll;............. .dWMMW0l,,,. .....    ........,:ox0XNWWX0kxo:;:dxl;::;,,,;,..   ........  .lNMMMMNOxl::loooc,'... .';,;lxO0KOo:,'............:dO00KXXOdoooddk0OO0dcodo:...''.....     .....   .':::'      
'::::'.             ......   ......    ...',;;,..   ..... ....',;;;,'..':lldxkkxkXMWXkdddlcc;,.......   .;;..lNMMMWNKkc..      ....    ':'.. ..,:coodxxxxdddkOxl;,',:ll:.         ....oXMMMWNkoodxO0OkkOK0c....',:loxkkOkdlc,..,;codxdlccd0NWWWWNkoodoodxOOOXk,,lo:......         ..      .,:::'      
':::::'.           ....      ..''..      .'::;cc,.....  ...',;:ok0KXKOxdxOxoccc;;oOXWNOdl:;;;,,;;. ..':clol'.oNMMMMWO;.''...... ....;cckXx:,........,:cccok0XWWKxocloooo'   ..,,,;'.;OWMMMNOxoccok0K0k0NMWKkd:'..';lxOOOkdoc;;oONWMMMMWNNNWMMMMWKkxxdoodO0K00O:'coc,.        ..............,:::'      
'::::::'.  .....   .....           ....   .'l0NX0Okd:'. ...... ...,:loxOKXKOkdolc;,,cdxdlc:;:ldkd' ...:l:,..:KMMMMMXo,'::;c:,.   ...;oOXMWKxc:cll;..',,;o0WMMMMN0xddkkddc. ..,clc;,lXMMMMWKkolodkkOKOOOKNMMMWN0xl;,,;;;:codxkkxxxOXWMMMMMMMMMWN0kkOkxddkXNNX0d;,c:'..        ..':dO0KKKK0kl'.;:'      
'::::::'. .....    ....             .::.   .,OMMMMW0c.. .............''.,:lllccc;'...':cllccokkko. .,;::,..;OWMMMMNk:;;,':OO:co:'...';coxxxx0WWWWNKKXXXXNMMMMMMMXOkkkxxdo'.',:;..;kNMMMMX0OOxddddOKK0kk0NMMMMMMMWKOxxxxOKNWMMMMWNNNMMMMMMMMMW0kkooxxk0OO0KXKOl',,.......     .:d0NNWWNXKKKKx;.''      
';,,''....'''.      .            .'';oc......dWMWMWl................;Ok:'......''.......,clldkkkl...';:;..,OWMMMMXxc::cc,'dXKXMW0occlccclx0XWMMMMMMMMMMMMMMMMMMMNKOOxdddc..,::,,dNMMMMMMXOOklccccodxO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWXOxxxxOKXXXX0kkxc...........   .cxxdoxOdc;'.',;l:..      
..   ...'.....              ...  .:lddc,''...xWWWMWOccc:;.....':cdO0XWKkddoc'..'........':lxO00x,,c:c:,..'xWMMMMW0olodxkddKMMMMMMWKxdood0NWWWWWWWMMMMMMMMMMMMMMMWKOOkddc..';;.'xWMMMMMMMNKOkxxOOOkdlo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXKXXXXKOkOKNNXNNXK0kx:....... ...  .,cc:;;:'..,,'.  'c,.      
..    ......              ....... ..;c:;,'..oNMMMWNOxxkkxlcc,..'',coodOX0Okdl:d0xccllloxdodO0KO;.;dkxl;;,lXMMMMWX0OO0K0Ok0NMMMMMMMMWNK0kkOO0XNNWMMMMMMMMMMMMMMWNKOOOkxc.,oxdo,:XMMMMMNX0kOO0XWMMMMMN0xdkKWMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKKX0OO000XWWNXNXK0ko'..........'...';;,,'. .:ll:'. .,'.      
'.                       .:ol'....,lxdl:;..lXWWMWNOxxxkOkdd00:...',,;:d0OOKXKNWMWWWWX0XWWNKOOOl..':loc:;cKMMMMWWXK0O000kooxKMMMMMMMMMMMMWNXNWMMMMMMMMWWMMMMMWNXK0OOOkl..:okkkc':dkkxdl;'.':d0XNWMMMMWXd,,lOXWMMMMMMMMMMMMMMMMMMMWWNNNNNNNXXXK0OOOkKNNXXX0OOkoc::cccl:,:xOo;',,,'....':dkkl. ....      
';.                     .cxkko,..,:llc;,'.cXMWWWWXkxxkOOxddxXKl,';:lddk0KXNWWMMMMMMMMMMMMWKOxd:...':cc;cKMMMMMMWXOklloddc:ckXWMMMMMMMMMMMMMMMMMMMMMMNKKXXWWWWNK0Okkdl' .;coddc..........;;'':cldkOKNNKd,..,dXMMMMMMMMMMMMMMMMMMWNNNNNNXNNNNXK0OkxxO00O0OkkkxooooooolccdKW0:',,...;c::oOXXx' ...'      
':,.                   .,okkkdc,..',;;;,,cKMMMWNK0kxkkkxddxOXWWKOxdk0KXWWWWMMMMMMMMMMMMWNKOxdo;...;lol,dWMMMMMMN0OOxolodddxkl:kWMMMMMMMMMWXKKXXXK0OOOOOkkKWNKOkxdol:,. .,coddc.........;oc.......':okxc...,ckXWMMMMMMMMMMMMMMMMWWNNNNNNNXKKKOOkxxxkkkxddddllccoooolcloxKWXl.'.. .;lx0KKKkc. ..''      
':;'.                  .'cldxxdo:;::;:,,dXMMMMWXOxxollodxk0XWWWWWWX0OOXWWMMMMMMMMMMMMWNKOOkxol,..'codo,,kNWNNX0kddxxkKNNWWMW0c,oXMMMMMMMMWXKOxdl:::coooxkOOkdol::;;,'. .'cdxxl....   ..';,.','....'';;.'col;:dKWMMMMMMMMMMMMMMMMMWWWWNNKOOkdddxxdxxolc;;:;,;;:loollc:;cOWMK:... ...';ccol,....;'      
'::;'......            ..':ldxkdool::;'dNMMMMMMNOxdoooooxkkdd0NWWWWWWNWWMMMMMMMMMMMMWWX0OOkoc:'...,::c,.':cc:;,,;;;:oOXWMMMMM0,.lKWMMMMMMMMMXkocc:::::clollc:,'.'..... .;codo;...   .  .....'.''....',l0NNN0l;o0NWMMMMMMMMMMMMMMWWMWWNX0kkkdddddol:;;;;:::;;;;:;;;,,',lKMMXl....   ..;:lc'...,:'      
':::::::;'.              .';coxxdolc:':0MWMMMMMNkdodkOOkkkOd:;dKWWWWWWWWWMMMMMWXNWMMNX0kxkdl;,....',,,'.......','.....;ldkO0Oo,.,oOXWMMMMMMMNKOkxxdlc:::;,,,'...........,::c;'''.';',,..,cc:;,..'';okKWMMMMMNxld0XWWMMMMMMMWWWWWNNWNXKK0Okxddoll:;:::::::;;,,''''',,,c0WMWx,....   .,clo:'...::'      
':::::::::,..           ..';loxkxoooc.,OWWMWNX0xclokNWWN0000o''c0WWWWWWWWWMMW0xddk00kdoool:,.... ...,::'..   ..,'...   ...''.'oxlco0NMMMMMMMMMWWNXOoollc;,,,,,'..........,;;,',:ldooo,',lk0k:':;;::cxKWMMMMMMWOlokKKKKNWWWNWWNXXKK0Okkkollllc:;;,,,,,;,,'''..''''';:ckNXkc'''...  ..;lc;;:'.;::'      
':::::::::::;'.         ..':oxkkxdc;'..,oxkxoc;'.',:ldk0kxxdl'.'ckXWWWWWMMMMWOlcclloolllc,.....  ....'....     .....   .....,xNMNOolONMMMMMMMMMMMW0xooooc;;:c:;;,'..... ....,lkkocdx:..,lxk0d':l:cll:cdkKWWWMWKo:lxxkOOOOKXXK0OO0Okxxdlccc:;;,''''''','''''.'''''':cxNK:..;lll;....,:,.,:;';:::'      
':::::::::::::;'....   ....,:oooc;'. ......''.........'',;;;,:lddllk0KXWWMMMMWXKOxolllc;'......   ........         .......;d0WMMMMXdck000XNWWMMMMMNOoxkko:;cl:;:,..,::.  ..co:;'..,;...;;...'..,',lol:;,cO00KNWXklcoxxddoodxxxxxkxxdolccll:,',,,'..'''''''..'''..,lkXWXkdxKNXKxc:,.....,'.,::::'      
':::::::::::::::;,,.    ...'',;,...  ..........'.. ........'dNWWWXd:;:lx0XXWWMWNKOkdolc:,.....  .;clllcc;..... ......''',:coONMMMMMXd::odxkk0NWMMMWNKX0o:;;::cc:;..:l:.   .:'     .,:c::,.     ...;coc'.';llcoxx0K0K0xlc::clloddolllcccc:::;,,,;,''''''''''',;;;;:xNWXxOXOxo:,...........,:::::'      
':::::::::::::::::'.    ...'''......''..     .... ....,::;,,xKOKWWW0c..,ldk0KXX00Okxoc:;'.....':dO0KXXKkdlc:'..;::,,cO0kxxl::lkNMMMMW0l;;codk0XNNNXK0Okd:;:ckXNXd':kd,.   .'.      ....           ..','''....''':OO0WXk:'',:lolc:;;:cc:;;;;;,'',,','''''',:ccloolxXMMWOoxkd;..';:;'....';::::::'      
':::::::::::::::::,.     ..'''........     .....,:::dOXNNNX0OKKOKNKKXx,.',codxkkkkxdl:,''...,cd0XX0NWMX0NXOc';odoloxXWNNXXXKKkkNMMMMMMNx;';lddxxxxddooddollOWMMMKd0Wk'.  .',.   ..;::;:ccllc;,...     .....'..,,,:,,kNWKl'',l0Kkc,;;cdxoll:,'.,;,'',,,,,codddooollkXWMNKOOkdccc:,....';::::::::'      
'::::::::::::::::::,.    ..'.... .............':odx0WWNNWWWWWWWWWWXkol;...',::codooolc;'..'lxOKNKx0WMNOONKkxk0NNXXXNMMMMMMMMMMMMMWWWWWMW0c';:clllllllodxO00NMMMMXKWWk,. .';.   .;dXWWWWWMWXkoclc,......   ..',,'';;,;d0NNOO00XWWKdc:coOOxdl;,.,;;;:cc:coddddooool;':dkOkxddl:,....,;:::::::::::'      
':::::::::::::::::::'.   ......';clll:;'''''.',;,:xKWNO0WMWWWWWWWWWW0l'.'..';,;:c::cc:,'..l0XWW0lxNWXocOKkdkKWMMMMMMMMMMMMMMMMMMWNNN0xONW0c',:::cclllk0OXN0KMMMMWWMWNx' 'c,.. .'lkKXXKKKKKOdldxdc:;;:c:;.     ....',;;;cdONMMMMMMNOk0K0Okxl;;;,;;::clodxxddoodooc.....';;;;'. ..;::::::::::::::'      
':::::::::::::::::::,. ...;::ldddooooc,..'....''..l0NKddKXNWWWWWWWWWWNOddc,'',,'''''',,..cKWMW0c:xOkc.,lddocoXMMMMMMMMMWNXNMMMMMWWWWXd:l0W0dllxxdolcoKWKXXOKMMWWMMKkKx;......  ..,,,''',;;'..............      ....  ...'xNMMMMMMMN0KN0Okxc;;;,,;::cldxxddodxxoc'.     ..... .';:::::::::::::::'      
':::::::::::::::::,'. ..;lx0KXKxll:;cc. ...   .....:dkxolox0OKWX0XMWMWWNX0x:'''......,'.'OWWMXl,lko,..';:;,':0MMMMMWWNNKkxKMMMMMMMMMMNOdoOOkKNWWNOllOWMNNWXNMMXNMXo;:;',.     ....';,'.'xKl..,,............   ........:lOWMWXXNWMMW0k00Oxdc,;;;;::cclodddddxxoc'';'.        .':::::::::::::::::'      
'::::::::::::::;'..   .:dOXNNXkc;;;....   ...........,coc,:oc:xkoxXWWWWMNKKOl:'.....''..cXMWW0c':xc....,,.',c0NKNMMWNNKdcOMMMMMMMMMMMMMW0docoNWWWXKXNMMMMMMMMMNX0oll;.';,.    ....;odl..dNXo;:;...;lc:,'''...        ;KMMMMXkdd0WMMXkdxkdol;,;;;:cllodxxddxxoc''xWXk:.      .;:::::::::::::::::'      
'::::::::::::::'.    .:x0K000xc;.....    ..',colodl;,...'..,,'':::oOK0ONWX0KOol'........xNK0Od:..c:....''..'cOx:kWMNKOl'lXMMMMWWMMMMMMMMWk;,;cONWWNOONMMMMMMMNOdoclkd,.',.    ....',lc..';oo::c,.,dkkxdooc'.....     .oXWWWKxolOWMMNOooolc;',;;;::ldxxxddddoc',xNMW0l'..   .;::::::::::::::::::'      
'::::::::::::::'.  ..,oOOkdlc:,,'. ..    .,,,oOOKN0l;,'..   ..',,,,cddldXWNKKkdc.......l0kdolc'  .... ......'c;.;OWKx:',l0NWW0oOWMMMMMMMM0:':,'lkKMKd0MMMMMMMN0xdlcdxc'...   ..,:c:lOxccl:,'.'co;;ooodl:,,,..',;,.....,oO0kdooodKWWXxcc::;,,,,,;;:oddxddddo:';OWMNOo;...  .':::::::::::::::::::'      
':::::::::::;,,.. ..'lkxo:;,,'....      ..,:oOX00XXOkkOxc;;,'......,ldc,ckKXXK0ko:...;kOocc;;;.             .'.. .d0:.,..:kKO:,OMMMMMMMMMO,,dl...oWWK0NWMMMMMMWXdcclll:.. .,cdxddkOxk0xddddoc;cdddxdc;'.;ddl;;kNKc;;',:odxdoloocxKxlc:;,,;,,,;;;cooddddxdl;.:KMMWOo:'..   .;:::::::::::::::::::'      
':::::::::::.......;ldoc;,'.....        ...:llcckXkoddkk;.'....   ...;:'..;ldk000kdldKKdc;.....              ...  .:c..,..,::;;kWMMMMMMMM0llOx,..:XMWNKXWMMMMMMW0kkl,cc. .cOXN0xkOl:ONXOdooxOkxkKXNKkol;;kNWXXWMWOc::clooodxkxoldo:;;;;;;:::;;:codddddxo:'.;OWMWKxc;'... .'::::::::::::::::::::'      
':::::::::::'...';:ll:,'''....    .;c:,''';c:'.l00x:,;;::,;:c,.       ......'';coodKNkl;'''..           ...         .. .....;oclKMMMMMMMWKOxkd'..cXMMMNOKWMMMMMMMMNo.',..;dO00odkl,,o0WWKOk0WWNWWMMW0dc;''oXMMMMMXd:c::ldxxddolol:;,;:::cc:cccooddddodo;..lKMMWXxl:,...  .;::::::::::::::::::::'      
':::::::::::,.';;;;,'........   .,coOXX0xlcclcd0xo00l,,,:lxOKOl'.       .....','..:Ox;,...''..  ....   .';;.   ..           .;c:lKMMMMMMWKkdc;...lXWMMXolXMMMMMMMWKd:;'..;lc',:'.''..,OWWKdd0NWWNX0kdoc,...c0WMMW0lcccldkxooooc;:::cccloolloooollcc:;,'..oNMMWXOoc;'..   .';;::::::::::::::::::'      
':::::::::::;. ......       ....'lxxxkOkxO0Ok0KkldKXXxc::lddk00xc. ...   .....,,..;o:........  .';'...',:l;.      ........   .::;l0WMMMMMXOl:;...cx0NWx',dXMMMMMMNxc::. .''. ... .....cOOc,;cxOkxooooolc'...oNMW0lcclodddddol:;;;:ccccllollllc;;,,'. ...:KMMWN0o:;,..     ...';::::::::::::::::'      
'::::::::::;...,..       ...,;;;;:cc:cod0WMNXNKdxXWWWWXOkxdxOKK0x,....        ....,c,......  ..;l:..;lllc,..,.     .'..,,..   '::,:xXWMMMWNOo:,,,:oONNd''c0WMMMMMNkcc:'....  ..    ..,oxo,..,lolc::llcclllc;lxxc,',:cc:coc:;,,;;,,',,;;;,;;;'...... ..;dKWMWXOo;'...   'l,   ..::::::::::::::::'      
':::::::::,. .;:,..    ..',;coxkkxxxxOKXWWXO0NNkllkNWWWWWNNNWWWXklc:'.         ...,:.   ..  .':dx;.'dk0k;..:ool;....'',:c:.   .,c;..cOXWMMMWKdldkkddXWN0xo0MMMMMMMNXOd;. ......    'odo:.. .'cc::;,,;ccll:'.........'..'.......'...'',,'......    .,oONMMWN0koc;'.... .cNk.   .,:::::::::::::::'      
':::::::;'.  ....    .:kOxddxO0XWWWWWWMMWKxxdOWKl;cOWWWWWWWWWWWKdlodoc:;..      ..;:.     .':lxkOl;xK0Kx'..,lk0X0:...,,,cl;.   .:o:';clxKWMMWOx0KKOx0WMMWK0XMMMMMMMMXkc. ... .....,cl:.. ...;cc::,...:cc;','..............     ........        ..,ckXWMWNKkdoc::;'. .'oXWO'   .':::::::::::::::'      
':::::::,.      ....,oXWMWWNNWWWWWWWWWMWWKo;oXWO;;o0WWMMWWWWWWWXOxxkO0XXx:'.  ..';:,.   .,codk00xcxNMNX0o....:OWMXc..,l',do,... .,l:'''':xXMWOddxx0WWMMMMMWWMMMMMMMMXxc. .'...'.',:cc;....';;;;,....',''..'...........                     ...';cd0NWWWN0xoc;'.....;xXWWk,     .,::::::::::::::'      
':::::::,.   ...,cdOKWWWWWWWWWWWMWWWWMXkxl;dXWWkcoOXWWMMMWWWWWWWNXKKXNWMWNx,..''.... ..,cok0KKOdd0NNWMNKO:.';oXWWWx...'.'k0o;;,.  .,;'...,dXMNklcldKWN0KWMMMMMMMMMMMW0l,..'. ..',:cc;. .........''..                                      .';cldkXWWWWXOdl;'....'ckNMWKl.       ..,::::::::::::'      
':::::::,.  ...;ok0KWMMWWWWWWMWWWWMWWWd'.;kWMMMWXXNWMMMMMMMWWWWWWWWWWMMMMNo....    .':okO0XXkl;c0WNWWMWNKklkNWMMMW0c.;kkOXXK0xl,.   .''''',ckKXXXXXOo;.oWMMMMWNWMNKNWNKd'..    ......  ..      ..                                     ...,:clox0NWWWWXOd:,'..;lxKWMMNx,. ..       ..;::::::::::'      
':::::::.  ....:xOKNWWMMWWMWWWMMMWMWWNo.,kWWMMMWWWWMMMMWWWMWWMMMMMMMMMMMMWO;.    ..cx0OdkNNx::lONWWMMMMMKk0WMMMMMMNk,:KMMNxdXNKx:.    .,::,,,,,;;:;...cKMMMMMWNWMXKK0XWNxcc;......                              ......        ..    ...'cooddkKWWMWNKko:'';lkXMMMMWO:.              ..;::::::::'      
'::::::,.  ....,ldkKWWMWWWWMWWMWX000Oo'.oNWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMK:....,oKX0OOXWO;;lkXWMMMWWM0lkWMMMMMMMMWKddKWMNxlxXNOc'... ..'........'cokXMMMMMMMMWNKKOddKWOlll::::,.          ..                 .........  .  .......',;ododxkKWMWNKkoccloxKWMMMMWKo..                 ..,;:::::'      
'::::;'.    ..,:cc:lx0XWWWMWNX0kddo:'..,ONWWWWWWWWWWWWWWWWWWWWWWWMWWWWMMMMMW0c..cx0XkkXMWWx.,d0NWWMWOOKloNMMMMMMMMMMMMKx0WMW0o:okxdl:;.        .'lXWMMMMMMMMMMMWX0ko:cdd;';:;:,'..      .''......              ............... ..'',:ldoodxOKNNXOdollx0XWMMMMMW0o,..                    .,:::::'      
':::;.     ..;lloc::ccoOKKK0Okkkxl;';,,xNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMNx;.:kNW0oxNMWMXc;0WXXNMWxdxoONMMMMMMMMMMMMMKdkNWMWO:,lxxol,..      ..oWMMMMMMMMMMMMNOOOl;::::;::,.          :XK;.;:,'...          ..',,,,.....'''...',;:looodkOKX0xlclx0XWMMMMMMNkc..                      .'::::::'      
':::;.   .',:lc;:ccccoxxkkkkkkkxl,,ld::ONNWWWWWNKXNWWWWWWWWWWWWWWWWWWWWWMMNd''lONW0loKWMMWWKOXMWNWWMOdOOOXMMMMMMMMMMMMMMKol0WMW0ooOX0xd:'.    ...,OWWKKWMMMMMMMWK00d:::cclc;.          .dWWx..:lc;,.....      ...',;;,,''''''.',:::cllldkkxolodk0XWMMMMMMWKx:..  ...                  .,:::::::'      
'::::'.  .''.''. .':cloooddoclol;,;,,;lxkKWWWWWNOk0kOXWWWWWWWWWWWWWWWWWMMKc.'lxkxxl:kWWMWXXWMMMMMMMMK0NK0WMMMMMMMMMMMMMMMNKXWMMWNXNMWKko:'...    .lKNd,:kWMMMMMNNWXklollcc;..          .xMMNl...:ol,.....      ....';;;,,'''..,c:,;:;;:;;:coOXWMMMMMMMMWKd;... ..''.                 .;::::::::'      
'::::;. ..... ..   .,:cc::;,,'..',. .cxll0WWWWWWOol:cdkXWWWWWWWWWWWWNNWMXl...,;;;ccxNWWKkXWMMMMMMMMMWWMWWMMMMMMMMMMMMMMMMMMMMMMMNXNMMWXkl:;'.......:xkc.'xWMMMWKXWW0xoodl:,..          .OMMMK:...;ol;....   . ...  ..';;;,'...,;'',,;codkKWMMMMMMMMMMN0d,..   ...'.                .'::::::::::'      
':::::'.   ......   ..''........... .okolkNWWWWXxlllooldKWWWWWWWWWWKO0KNKc. ...:dx0NMMMkl0WWMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMXOKMMMMW0occ:clll:,;oxdc,;oOKWWNNNN0xdolc;..           ,0MMMM0c,;,,;:;,'...          ...'....':::cox0NWMMMMMMMMMMMWX0k:...  .....                 .,:::::::::::'      
':::::,. ...  ..     ....   ....... .oo:,oXWWXOdllccoxxx0WWWWWWWWWXOxxxxkl. ...:O0OXMMMNXNWWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMWKkxdxO000OO000Oxl;,,cxXWNKkdddxx:..           ,KMMMMMWNNN0o:;:::,..   ...........',:ldkKNMMMMMMMMMMMMMMWNOoc;..   ....                  .;::::::::::::'      
':::::;.  ..  .               ....  .;...dNWXxllll::lxOOXWWWWNXK0Okdoooooc. . .lKo.:OWMMWMMWWMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKNWWWWWWWMXxoldo'.lNMNKOkk0O;.            .oNMMMMMMMMMMNKOxooo;...........:dOKXNMMMMMMMMMMMMMMMMMMNOo:....   ...                  .'::::::::::::::'      
':::::;.                     ....   ...''oOKKxlllc;:ldddOKKKOkxdoolooool;......:x:..:0NWMMMMMMMMWWWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKXWKkd,'ol..cxk0K000o.              .dNMMMMMMMMMMMMMWWXOo;.':::lx0KNWMMMMMMMMMMMMMMMMMMMMN0o,'...                         .,:::::::::::::::'      
':::::;.               ...   ..     ..',..;:dxl:;;;;:ldddolllcccccldl,'..     ..:dl;:loxOXMMMMWWWWMMMWK0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkKXX00Ol'.,.  ..'''...                .dNMMMMMMMMMMMMMMXx:..lk0KNWMMMMMMMMMMMMMMMMMMMMMMWKdc,'..                         .';::::::::::::::::'      
'::::::,'.                           .;;...';xd,''';cONX0kdllc:;,,:c'     ... ...'......cXMMWWWWWWWWWNddXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNMMNXOxOKK0kxxd;...   ....                    .oNMMMMMMMMMMMW0:..   ..',:cd0WMMMMMMMMMMMMMMMMMNklc:,.....','......            .';::::::::::::::::::'      
'::::::::.                         ...,'.....'lxl;,;cdKWWWXX0xc'.. ..     .'...........lKWMWWWWWWXKNXd,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKx0WMKkxdO000Okdd:...                        ..,..cXMMMMMMMMMMO,.           ..dNMMMMMMMMMMMMMMMMW0dc,...';::::;;,,,;,,'..      .,::::::::::::::::::::'      
'::::::::;'.                    ..''..........cKWX00OOKXWKxdOx;.          ...........;OWMMWWWWWWKOOkll;cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0oxNMXOkO0K0OkOKKo.         ....            .,::;'.:KMMMMMMMM0;.              .xWMMMMMMMMMMMMMMMMNk;..';::::::::::::::::;,.....;:::::::::::::::::::::'      
'::::::::::;'.                  ....  ...  ..'lkKWWMWWXk0k:cdd,            ...''..  .xWMMMWWWXXKOdc,',.'kMMMMMMMMMMMMMMMMMMMMMMXOKMMMMMMMNkloOKKKKXKOl'':dKO'        .,::;'..        .,:::::,.;0WMMMMMK:...''...         ,0MMMMMMMMMMMMMWXx:..,;:::::::::::::::::::::;,;;::::::::::::::::::::::'      
'::::::::::::;'. .....                       .,:oOXNNN0dko..;;.           .....''. ..lNMWWWWXOkkko'....xWMMMMMMMMMMMMMMMMMMMMWO:lXMMMWWMN0o;:dO0KKkc.   ..:0x,.      .,::::;'.      .,:::::::,.'dNMMMK:...;:::;;,'... ....:KMMMMMMMMMMNOl,..,;:::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::;,,;;;;,,'...           ....    ..,:oxkkxxo,.                ...'.. ..'kWWWWNKOxdoc..';kWMMMMMMMMMMMN0XMMMMMMNx,:0WMMWWWNNk,.,lxkOkc'..    .l00c.      .;::::;.    .';:::::::::;..;kNK:. .;:::::::::;,,;:;..oNMMMMMMNOo;...,;:::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::,'.    ...',;;:;,...   ..',,''..    ...           ..'.. ...:XMNKOOxdoc,.cOKWMMMMMMMMMMMWk;kMMMMMMXdoOXWMWNNN0kx;..'cooolc,.  ..  .'.      .':::::;'....,::::::::::::;'..:;.  .;:::::::::::::::'.'kMMMNOl,...',::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::;,'',;;:::::::::;;'..             ...  .......   .....   .dNWKxdoc,...dKNMMMMMMMMMMMMNd;OMMMMMMMWXNKxOXXKKOxdl,...,,;ldd:. ..         ..,;:::::::;;;;:::::::::::::::,.    .';:::::::::::::::'..:Okl,. ..,;::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::,'.             ..';;;;;:;,.  ''  ..  .:xKKOl....,kXWMMMMMMMMMMMMNl'lOXWMMMMMNXNx;cO000kxc'..,cc;':do'    .......,;::::::::::::::::::::::::::::::;'...,;::::::::::::::::'. ... ..,;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::;,,''.....''',;:::::::::;.   .. ..   ..:kXO' ...cKWMMMMMMMMMMWNXo...':dXMMMXOXXc..lkxl,.. .;:,'...,.  .';::::::::::::::::::::::::::::::::::::::::;;;::::::::::::::::::;,....,;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;:::::::::::::::;'.      .,.    .,lo,.::.cXMMMMMMWNK0kOOx;.....:KMMWKkd,..,l:'..   .         .,::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::,'.    .''      .,;;oo'.cKWMMXkdolloxOOOko:';:oKX0o,.   .....            .,;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;,.              . .. .;OWWx,''',;:ccdxdl,..,:,..                    .';::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'                   .,kO:........,;..              ..            .,::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;.                    'od:..    ..            ....';,.     ......,:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;'..                ..c0Nk,            ....',;;::::;....',;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;,'...  ..','..   .',;'.      ....',;;:::::::::::;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;,,;;::::;,'..   .....'',,;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;,,,;;;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'      
*/